#ifndef _WIFI_DAEMON_H
#define _WIFI_DAEMON_H

#define MAX_SSID_LEN 32

#define _ATTR_I6000_SHELL_               __attribute__((section("i6000_shell")))

typedef enum
{
    WIFI_DAEMON_STATE_DISCONNECTED = 0,
    WIFI_DAEMON_STATE_SCANNING,
    WIFI_DAEMON_STATE_SCAN_DONE,
    WIFI_DAEMON_STATE_CONNECTING,
    WIFI_DAEMON_STATE_CONNECTED,
    WIFI_DAEMON_STATE_DHCP_DOING,
    WIFI_DAEMON_STATE_IP_CONFIGED,
    WIFI_DAEMON_STATE_COMMAND_TESTING,
    WIFI_DAEMON_STATE_AUTO_CONNECT,
    WIFI_DAEMON_STATE_NUM
} WIFI_DAEMON_STATE_TYPE_E;

typedef enum
{
    WIFI_EVENT_TYPE_DISCONNECTED = 0,
    WIFI_EVENT_TYPE_SCANNING,
    WIFI_EVENT_TYPE_SCAN_DONE,
    WIFI_EVENT_TYPE_CONNECTING,
    WIFI_EVENT_TYPE_CONNECTED,
    WIFI_EVENT_TYPE_DHCP_DOING,
    WIFI_EVENT_TYPE_IP_CONFIGED,
    WIFI_EVENT_TYPE_COMMAND_TESTING,
    WIFI_EVENT_TYPE_AUTO_CONNECT,
    WIFI_EVENT_TYPE_NUM
} WIFI_EVENT_TYPE_E;

typedef enum
{
    WIFI_USER_CONNECT_AP = 0,
    WIFI_USER_DUMMY,
    WIFI_USER_ENTER_INTERACTIVE,
    WIFI_USER_DISCONNECT_WITH_AP,
    WIFI_USER_ACTION_MAX
} WIFI_USER_ACTION_TYPE_E;

void  wifi_daemon_task (void *p_arg);
rk_err_t i6000_wifi_dev_shell(HDC dev, uint8 * pstr);

#endif
