/********************************************************************
 This file was generated by menu Tool of Rockchip Co., Ltd.

 Generate time: 2016-3-30 9:36:56

 Tool Version: 3.0.0.0

 End.
********************************************************************/
#ifndef          _MENU_RESOURCE_H
#define          _MENU_RESOURCE_H


#define          MENU_ITEM_LENGTH            (unsigned short)248             // The length of menu item in bytes
#define          TOTAL_MENU_ITEM             (unsigned short)190
#define          TOTAL_LANAUAGE_NUM          (unsigned short)19
#define          MAX_SUBMENU_NUM             (unsigned short)16
#define          MENU_CONTENT_OFFSET         (unsigned short)48





#define          SID_MUSIC                                        (unsigned short)0x0000       //Music
#define          SID_DLNA                                         (unsigned short)0x0001       //DLNA
#define          SID_MAINMENU_BLUETOOTH                           (unsigned short)0x0002       //Bluetooth
#define          SID_AIRPLAY                                      (unsigned short)0x0003       //Airplay
#define          SID_5_1_CHANNEL                                  (unsigned short)0x0004       //5.1 Channel
#define          SID_RADIO                                        (unsigned short)0x0005       //Radio
#define          SID_RECORD                                       (unsigned short)0x0006       //Record
#define          SID_TEXT                                         (unsigned short)0x0007       //Text
#define          SID_EXPLORER                                     (unsigned short)0x0008       //Explorer
#define          SID_MAIN_SETTINGS                                (unsigned short)0x0009       //Settings
#define          SID_VIDEO                                        (unsigned short)0x000a       //Video
#define          SID_PHOTO                                        (unsigned short)0x000b       //Photo
#define          SID_FM_RADIO                                     (unsigned short)0x000c       //FM Radio 
#define          SID_GAME                                         (unsigned short)0x000d       //Game
#define          SID_NOR                                          (unsigned short)0x000e       //NOR
#define          SID_PLAYFX                                       (unsigned short)0x000f       //PlayFX
#define          SID_ROCK                                         (unsigned short)0x0010       //ROCK
#define          SID_POP                                          (unsigned short)0x0011       //POP
#define          SID_CLASS                                        (unsigned short)0x0012       //CLASS
#define          SID_BASS                                         (unsigned short)0x0013       //BASS
#define          SID_JAZZ                                         (unsigned short)0x0014       //JAZZ
#define          SID_USER                                         (unsigned short)0x0015       //USER
#define          SID_UNKNOWN                                      (unsigned short)0x0016       //~Unknown~
#define          SID_NO_LYRIC_FILE                                (unsigned short)0x0017       //~No Lyric File~
#define          SID_MANUAL                                       (unsigned short)0x0018       //Manual
#define          SID_PRESET                                       (unsigned short)0x0019       //Preset
#define          SID_MEM                                          (unsigned short)0x001a       //Add Preset
#define          SID_DEL                                          (unsigned short)0x001b       //Delete Preset
#define          SID_AUTO                                         (unsigned short)0x001c       //Auto Preset
#define          SID_REC                                          (unsigned short)0x001d       //Rec
#define          SID_PLAY_REC_DATA                                (unsigned short)0x001e       //Play Rec Data
#define          SID_DELETE_REC_DATA                              (unsigned short)0x001f       //Delete Rec Data
#define          SID_DELETE_ALL                                   (unsigned short)0x0020       //Delete All
#define          SID_ALL_REC_DATA                                 (unsigned short)0x0021       //All Rec Data
#define          SID_DELETE_ALL_COMFIRM                           (unsigned short)0x0022       //Delete All?
#define          SID_DELETING                                     (unsigned short)0x0023       //Deleting…
#define          SID_SAVE_CHANNEL                                 (unsigned short)0x0024       //Replace OK?  
#define          SID_DELETE_CHANNEL                               (unsigned short)0x0025       //Delete OK?
#define          SID_SAVE_BOOKMARK                                (unsigned short)0x0026       //Save BookMark
#define          SID_LOAD_BOOKMARK                                (unsigned short)0x0027       //Load BookMark
#define          SID_MIC_REC                                      (unsigned short)0x0028       //MIC REC
#define          SID_LINE_IN_REC                                  (unsigned short)0x0029       //LINE IN REC
#define          SID_FM_REC                                       (unsigned short)0x002a       //FM REC
#define          SID_RECORDING                                    (unsigned short)0x002b       //Recording...
#define          SID_RECORD_PAUSE                                 (unsigned short)0x002c       //Pause...
#define          SID_RECORD_PREPARE                               (unsigned short)0x002d       //Prepare...
#define          SID_RECORD_SAVE_FILE                             (unsigned short)0x002e       //Save File...
#define          SID_CREAT_FILE_ERROR                             (unsigned short)0x002f       //Creat File Error!
#define          SID_DISK_IS_FULL                                 (unsigned short)0x0030       //Disk Is Full!
#define          SID_FLASH_MEMERY                                 (unsigned short)0x0031       //Flash Memery
#define          SID_MINISD_CARD                                  (unsigned short)0x0032       //MiniSD Card 
#define          SID_COULD_NOT_CONTINUE                           (unsigned short)0x0033       //Could not continue
#define          SID_WARNING                                      (unsigned short)0x0034       //Warning
#define          SID_YES                                          (unsigned short)0x0035       //Yes
#define          SID_NO                                           (unsigned short)0x0036       //No
#define          SID_EXIT                                         (unsigned short)0x0037       //Exit
#define          SID_PLEASE_WAIT                                  (unsigned short)0x0038       //Please Wait……
#define          SID_LOW_BATTERY                                  (unsigned short)0x0039       //Low Battery!
#define          SID_FIRMWARE_UPGRADE                             (unsigned short)0x003a       //Firmware Upgrade?
#define          SID_PLEASE_INSERT_USB                            (unsigned short)0x003b       //Connect USB…… 
#define          SID_RESTORE_DEFAULT_VAL                          (unsigned short)0x003c       //Restorable?
#define          SID_FORMAT_DISK                                  (unsigned short)0x003d       //Format Disk?
#define          SID_FORMATTING                                   (unsigned short)0x003e       //Formatting……
#define          SID_FILE_FORMAT_ERROR                            (unsigned short)0x003f       //File Format Error!
#define          SID_NO_MUSIC_FILE                                (unsigned short)0x0040       //No Music File!
#define          SID_DELETE_FILE                                  (unsigned short)0x0041       //Delete File
#define          SID_DELETE_FILE_ASK                              (unsigned short)0x0042       //Delete File?
#define          SID_DELETING_FILE                                (unsigned short)0x0043       //Deleting File…… 
#define          SID_MUSIC_FILE                                   (unsigned short)0x0044       //Music File
#define          SID_VIDEO_FILE                                   (unsigned short)0x0045       //Video File
#define          SID_TEXT_FILE                                    (unsigned short)0x0046       //Text
#define          SID_PICTURE_FILE                                 (unsigned short)0x0047       //Picture File
#define          SID_EXPLORER                                     (unsigned short)0x0048       //Explorer
#define          SID_C_FLASH                                      (unsigned short)0x0049       //C:FLASH
#define          SID_D_FLASH                                      (unsigned short)0x004a       //D:FLASH
#define          SID_D_SD_CARD                                    (unsigned short)0x004b       //D:SD CARD
#define          SID_E_SD_CARD                                    (unsigned short)0x004c       //E:SD CARD
#define          SID_NO_FILE                                      (unsigned short)0x004d       //No File!
#define          SID_SAVE_BOOKMARK                                (unsigned short)0x004e       //Save BookMark
#define          SID_LOAD_BOOKMARK                                (unsigned short)0x004f       //Load BookMark
#define          SID_WRITE_FILE_ERROR                             (unsigned short)0x0050       //Write File Error!
#define          SID_CLOSE_FILE_ERROR                             (unsigned short)0x0051       //Close File Error!
#define          SID_MEDIALIB                                     (unsigned short)0x0052       //medialib
#define          SID_PLAYING                                      (unsigned short)0x0053       //Go to playback screen.
#define          SID_ALL_MUISC_FILE                               (unsigned short)0x0054       //All Songs
#define          SID_ARTIST                                       (unsigned short)0x0055       //Artists
#define          SID_ALBUM                                        (unsigned short)0x0056       //Albums
#define          SID_GENRE                                        (unsigned short)0x0057       //Genres
#define          SID_PLAY_LIST                                    (unsigned short)0x0058       //Playlist
#define          SID_DIR_LIST                                     (unsigned short)0x0059       //Folder
#define          SID_RECORE_FILE                                  (unsigned short)0x005a       //RECORE FILE
#define          SID_MY_FAVORITE                                  (unsigned short)0x005b       //My Favorite
#define          SID_UPDATE_MEDIALIB                              (unsigned short)0x005c       //MediaLib Update
#define          SID_UPDATEING_FIRMWARE                           (unsigned short)0x005d       //Firmware Upgrading…… 
#define          SID_RECOVER_FIRMWARE                             (unsigned short)0x005e       //Firmware Recoverying…… 
#define          SID_HOLDON_PLAY                                  (unsigned short)0x005f       //Breakpoint player
#define          SID_TITLE                                        (unsigned short)0x0060       //Title
#define          SID_ADD_FAVORITE                                 (unsigned short)0x0061       //Add To Favorite
#define          SID_CLEAR_FAVORITE                               (unsigned short)0x0062       //Clear Up
#define          SID_UPDATEING_MEDIALIB                           (unsigned short)0x0063       //MediaLib Update…… 
#define          SID_CONNECTING_USB                               (unsigned short)0x0064       //Connecting USB
#define          SID_CHARGING                                     (unsigned short)0x0065       //Charging
#define          SID_FULL_CHANGED                                 (unsigned short)0x0066       //Fully charged
#define          SID_CANNOT_CHARGE                                (unsigned short)0x0067       //Cannot charge
#define          SID_DATA_EX_NOT_DISCONNECT_LINE1                 (unsigned short)0x0068       //Do not
#define          SID_DATA_EX_NOT_DISCONNECT_LINE2                 (unsigned short)0x0069       //disconnect
#define          SID_DATA_EX_NOT_DISCONNECT_LINE3                 (unsigned short)0x006a       //disconnect
#define          SID_VOLUME                                       (unsigned short)0x006b       //Volume
#define          SID_UPDATING_LIBRARY                             (unsigned short)0x006c       //Updating Library
#define          SID_WIFI_TURN_ON                                 (unsigned short)0x006d       //Please turn on WIFI.
#define          SID_WIFI_TURN_OFF                                (unsigned short)0x006e       //Please turn off WIFI.
#define          SID_WIFI_TURNNING_ON                             (unsigned short)0x006f       //Turnning on WIFI……
#define          SID_WIFI_TURNNING_OFF                            (unsigned short)0x0070       //Turnning off WIFI……
#define          SID_WIFI_TURNON_FAILED                           (unsigned short)0x0071       //Turn on WIFI Failed!
#define          SID_WIFI_CONNECT_FAILED                          (unsigned short)0x0072       //Connect WIFI Failed!
#define          SID_BT_TURN_ON                                   (unsigned short)0x0073       //Please turn on Bluetooth.
#define          SID_BT_TURN_OFF                                  (unsigned short)0x0074       //Please turn off Bluetooth.
#define          SID_BT_TURNNING_ON                               (unsigned short)0x0075       //Turnning on bluetooth……
#define          SID_BT_TURNNING_OFF                              (unsigned short)0x0076       //Turnning off bluetooth……
#define          SID_BT_TURNON_FAILED                             (unsigned short)0x0077       //Turn on bluetooth Failed!
#define          SID_PLAYER_FAILED                                (unsigned short)0x0078       //Turn on player failed！
#define          SID_RECODING_STEREO                              (unsigned short)0x0079       //Stereo
#define          SID_RECODING_MONO                                (unsigned short)0x007a       //Mono
#define          SID_RECODING_BIT24                               (unsigned short)0x007b       //24bit
#define          SID_RECODING_BIT16                               (unsigned short)0x007c       //16bit
//-----------------------------------------------------------------------------------------------------------------------------
//-------This is a menu-------
#define          SID_SETTINGS                                     (unsigned short)0x007d       //Settings
#define          SID_WLAN                                         (unsigned short)0x007e       //WLAN
#define          SID_WIFICONFIG                                   (unsigned short)0x007f       //WiFi Power
#define          SID_WIFICONFIG_ON                                (unsigned short)0x0080       //On                    [Function Index: 0000]
#define          SID_WIFICONFIG_OFF                               (unsigned short)0x0081       //Off                   [Function Index: 0001]
#define          SID_APCONFIG                                     (unsigned short)0x0082       //AP Config             [Function Index: 0002]
#define          SID_BLUETOOTH                                    (unsigned short)0x0083       //Bluetooth
#define          SID_BLUETOOTH_ON                                 (unsigned short)0x0084       //On                    [Function Index: 0003]
#define          SID_BLUETOOTH_OFF                                (unsigned short)0x0085       //Off                   [Function Index: 0004]
#define          SID_SETTING_MUSIC                                (unsigned short)0x0086       //Music Settings
#define          SID_MUSIC_SHUFFLE                                (unsigned short)0x0087       //Shuffle
#define          SID_MUSIC_SHUFFLE_OFF                            (unsigned short)0x0088       //Shuffle Off           [Function Index: 0005]
#define          SID_MUSIC_SHUFFLE_ON                             (unsigned short)0x0089       //Shuffle On            [Function Index: 0006]
#define          SID_MUSIC_REPEAT_MODE                            (unsigned short)0x008a       //Repeat
#define          SID_MUSIC_FOLDER_ONCE                            (unsigned short)0x008b       //Off                   [Function Index: 0007]
#define          SID_MUSIC_FOLDER_REPEAT                          (unsigned short)0x008c       //Repeat                [Function Index: 0008]
#define          SID_MUSIC_REPEAT_ONE                             (unsigned short)0x008d       //Repeat 1 Song         [Function Index: 0009]
#define          SID_EQ_SELECT                                    (unsigned short)0x008e       //Equalizer
#define          SID_EQ_NONE                                      (unsigned short)0x008f       //Normal                [Function Index: 0010]
#define          SID_EQ_BASS                                      (unsigned short)0x0090       //Bass                  [Function Index: 0011]
#define          SID_EQ_HEAVY                                     (unsigned short)0x0091       //Heavy                 [Function Index: 0012]
#define          SID_EQ_POP                                       (unsigned short)0x0092       //Pop                   [Function Index: 0013]
#define          SID_EQ_JAZZ                                      (unsigned short)0x0093       //Jazz                  [Function Index: 0014]
#define          SID_EQ_UNIQUE                                    (unsigned short)0x0094       //Unique                [Function Index: 0015]
#define          SID_EQ_CUSTOM                                    (unsigned short)0x0095       //Custom                [Function Index: 0016]
#define          SID_SETTING_RADIO                                (unsigned short)0x0096       //FM Settings
#define          SID_RADIO_SCAN_SENSITIVITY                       (unsigned short)0x0097       //Scan Sensitivity
#define          SID_SCAN_SENSITIVITY_HIGH                        (unsigned short)0x0098       //High                  [Function Index: 0017]
#define          SID_SCAN_SENSITIVITY_LOW                         (unsigned short)0x0099       //Low                   [Function Index: 0018]
#define          SID_FM_AUTO_PRESET                               (unsigned short)0x009a       //FM Auto Preset        [Function Index: 0019]
#define          SID_SETTING_COMMON                               (unsigned short)0x009b       //Common Settings
#define          SID_COMMON_SCREEN_OFF_TIMER                      (unsigned short)0x009c       //Screen Off Timer
#define          SID_SCREEN_OFF_15_SEC                            (unsigned short)0x009d       //15 Seconds            [Function Index: 0020]
#define          SID_SCREEN_OFF_30_SEC                            (unsigned short)0x009e       //30 Seconds            [Function Index: 0021]
#define          SID_SCREEN_OFF_1_MIN                             (unsigned short)0x009f       //1 Minute              [Function Index: 0022]
#define          SID_SCREEN_OFF_3_MIN                             (unsigned short)0x00a0       //3 Minutes             [Function Index: 0023]
#define          SID_SCREEN_OFF_5_MIN                             (unsigned short)0x00a1       //5 Minutes             [Function Index: 0024]
#define          SID_SCREEN_OFF_30_MIN                            (unsigned short)0x00a2       //30 Minutes            [Function Index: 0025]
#define          SID_COMMON_BRIGHTNESS                            (unsigned short)0x00a3       //Brightness
#define          SID_LUM_1                                        (unsigned short)0x00a4       //1                     [Function Index: 0026]
#define          SID_LUM_2                                        (unsigned short)0x00a5       //2                     [Function Index: 0027]
#define          SID_LUM_3                                        (unsigned short)0x00a6       //3                     [Function Index: 0028]
#define          SID_LUM_4                                        (unsigned short)0x00a7       //4                     [Function Index: 0029]
#define          SID_LUM_5                                        (unsigned short)0x00a8       //5                     [Function Index: 0030]
#define          SID_SYS_ABOUT                                    (unsigned short)0x00a9       //Information           [Function Index: 0031]
#define          SID_LANGUAGE                                     (unsigned short)0x00aa       //Language
#define          SID_CHINESE_S                                    (unsigned short)0x00ab       //简体中文              [Function Index: 0032]
#define          SID_CHINESE_T                                    (unsigned short)0x00ac       //繁體中文              [Function Index: 0033]
#define          SID_ENGLISH                                      (unsigned short)0x00ad       //English               [Function Index: 0034]
#define          SID_KOREAN                                       (unsigned short)0x00ae       //??                    [Function Index: 0035]
#define          SID_JAPANESE                                     (unsigned short)0x00af       //日本語                [Function Index: 0036]
#define          SID_FRENCH                                       (unsigned short)0x00b0       //Fran?ais              [Function Index: 0037]
#define          SID_GERMAN                                       (unsigned short)0x00b1       //Deutsch               [Function Index: 0038]
#define          SID_PORTUGUESE                                   (unsigned short)0x00b2       //Português            [Function Index: 0039]
#define          SID_RUSSIAN                                      (unsigned short)0x00b3       //Русский        [Function Index: 0040]
#define          SID_SWEDISH                                      (unsigned short)0x00b4       //Svenska               [Function Index: 0041]
#define          SID_THAI                                         (unsigned short)0x00b5       //???????               [Function Index: 0042]
#define          SID_POLISH                                       (unsigned short)0x00b6       //j?zyk polski          [Function Index: 0043]
#define          SID_DENISH                                       (unsigned short)0x00b7       //Dansk                 [Function Index: 0044]
#define          SID_GREEK                                        (unsigned short)0x00b8       //Ελληνικ?       [Function Index: 0045]
#define          SID_CZECHIC                                      (unsigned short)0x00b9       //?í?tina              [Function Index: 0046]
#define          SID_TURKISH                                      (unsigned short)0x00ba       //Türk?e               [Function Index: 0047]
#define          SID_SETTING_INITIALIZE                           (unsigned short)0x00bb       //Initialize
#define          SID_SYS_DEFAULT_SET                              (unsigned short)0x00bc       //Reset All Settings    [Function Index: 0048]
#define          SID_FORMAT_DISK                                  (unsigned short)0x00bd       //Format                [Function Index: 0049]





//-----------------------------------------------------------------------------------------------------------------------------
#define          SID_SETTINGS_ENTRY                               SID_SETTINGS       //Settings
#define          SID_SETTINGS_ENTRY_FUN_COUNTER                   0x0032


#endif
