#!/usr/bin/env python3
"""
cleanup_c_files.py — Clean and make-compilable the Ghidra-decompiled .c tree.

Steps:
  1. Inject `#include "decomp_support.h"` into every decompiled .c that
     lacks it (skips the SDK reference trees rockchip/ and rockchip_wireless/).
  2. Scan all decompiled .c for referenced global symbols (DAT_*, FUN_*,
     thunk_*, s_*) and emit a single `decomp_globals.h` declaring each as a
     weak extern so the tree compiles with -Wl,--undefined tolerated.
  3. Optional: --syntax-check compiles each file (arm-none-eabi-gcc -fsyntax-only)
     and writes a report build/compile_report.json.

Usage:
    python tools/cleanup_c_files.py            # inject includes + build globals
    python tools/cleanup_c_files.py --check    # also syntax-check each file
"""
from __future__ import annotations

import argparse
import re
import subprocess
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FIRMWARE = ROOT / "firmware"
GLOBALS_H = FIRMWARE / "decomp_globals.h"
SUPPORT_H = "decomp_support.h"
FUNCS_H = FIRMWARE / "decomp_funcs.h"

# Trees that are SDK reference source, NOT decompiled output
SKIP = ("rockchip", "rockchip_wireless", "unidentified")


def decompiled_c_files() -> list[Path]:
    out = []
    for p in sorted(FIRMWARE.rglob("*.c")):
        rel = p.relative_to(FIRMWARE)
        if rel.parts[0] in SKIP:
            continue
        out.append(p)
    return out


def inject_include(path: Path) -> bool:
    text = path.read_text(encoding="utf-8", errors="replace")
    need_globals = f'#include "decomp_globals.h"' not in text
    changed = False
    if f'#include "{SUPPORT_H}"' not in text:
        # insert after the last #include or right after the header comment
        lines = text.splitlines(keepends=True)
        anchor = 0
        for i, ln in enumerate(lines):
            if ln.startswith("#include"):
                anchor = i + 1
        lines.insert(anchor, f'#include "{SUPPORT_H}"\n')
        text = "".join(lines)
        changed = True
    if need_globals:
        # insert decomp_globals.h after the support include
        text = text.replace(f'#include "{SUPPORT_H}"',
                            f'#include "{SUPPORT_H}"\n#include "decomp_globals.h"')
        changed = True
    if changed:
        path.write_text(text, encoding="utf-8")
    return changed


def collect_globals(files: list[Path]) -> tuple[set[str], set[str], set[str]]:
    dats, funs, strs = set(), set(), set()
    oths = set()
    for p in files:
        text = p.read_text(encoding="utf-8", errors="replace")
        # DAT_ / _DAT_ (Ghidra sometimes emits a leading underscore),
        # FUN_ / _FUN_, s_ / _s_ strings
        dats.update(re.findall(r"\b_?DAT_[0-9a-fA-F]+", text))
        funs.update(re.findall(r"\b_?FUN_[0-9a-fA-F]+", text))
        strs.update(re.findall(r"\b_?s_[A-Za-z0-9_]+", text))
        # Ghidra RAM/register globals: uRam, bRam, wRam, dRam, g_* named globals
        oths.update(re.findall(r"\b[uUbBwWdDqQ]Ram[0-9a-fA-F]{6,}", text))
        oths.update(re.findall(r"\bg_[a-zA-Z0-9_]+", text))
    return dats, funs, strs, oths


def write_funcs_h(files: list[Path]) -> None:
    """Declare every named function so cross-file calls compile.
    Extract just the function name; declare old-style `int name();` so any
    call compiles regardless of the true signature."""
    names = set()
    for p in files:
        text = p.read_text(encoding="utf-8", errors="replace")
        body = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
        m = re.search(r"(?:^|\n)\s*[\w\*\s]+\b(\w+)\s*\([^;{}]*\)\s*\{", body)
        if m:
            fname = m.group(1)
            if not fname.startswith(("FUN_", "thunk_", "LAB_")) and \
               fname not in ("__attribute__", "asm", "inline", "static"):
                names.add(fname)
    lines = [
        "/* decomp_funcs.h — auto-generated by tools/cleanup_c_files.py",
        " * Cross-file declarations for named functions (old-style, so any",
        " * call compiles). Exact signatures are reconstructed later. */",
        "#ifndef DECOMP_FUNCS_H",
        "#define DECOMP_FUNCS_H",
        "",
    ]
    for name in sorted(names):
        lines.append(f"int {name}();")
    lines.append("")
    lines.append("#endif /* DECOMP_FUNCS_H */")
    FUNCS_H.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_globals_h(dats, funs, strs, oths) -> None:
    lines = [
        "/* decomp_globals.h — auto-generated by tools/cleanup_c_files.py",
        " * Weak externs for every global symbol referenced by the",
        " * Ghidra-decompiled sources. Compile-check only; real definitions",
        " * come from the memory map reconstruction. */",
        "#ifndef DECOMP_GLOBALS_H",
        "#define DECOMP_GLOBALS_H",
        "#include \"decomp_support.h\"",
        "",
        "/* DAT_xxxx: weak data symbols as 1-element arrays, so both",
        "   *DAT_x (deref) and DAT_x + n (pointer math) compile. */",
    ]
    for d in sorted(dats):
        lines.append(f'extern uint32_t {d}[1] __attribute__((weak));')
    lines.append("")
    lines.append("/* FUN_xxxx: weak symbols with UNSPECIFIED params (old-style), so any")
    lines.append("   call compiles; returns int. Bodies are reconstructed later. */")
    for f in sorted(funs):
        lines.append(f'extern int {f}() __attribute__((weak));')
    lines.append("")
    lines.append("/* s_xxxx: string literals (declared weak char arrays) */")
    for s in sorted(strs):
        lines.append(f'extern char {s}[] __attribute__((weak));')
    lines.append("")
    lines.append("/* uRam/…/g_*: Ghidra RAM registers and named globals */")
    for o in sorted(oths):
        if o.startswith(("uRam", "bRam", "wRam", "dRam", "qRam")):
            lines.append(f'extern uint32_t {o} __attribute__((weak));')
        else:
            lines.append(f'extern int {o} __attribute__((weak));')
    lines.append("")
    lines.append("#endif /* DECOMP_GLOBALS_H */")
    GLOBALS_H.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--limit", type=int, default=0, help="max files to syntax-check")
    args = parser.parse_args()

    files = decompiled_c_files()
    print(f"decompiled .c files (excl SDK/unidentified): {len(files)}")

    injected = 0
    for p in files:
        if inject_include(p):
            injected += 1
    print(f"injected #include \"{SUPPORT_H}\": {injected} files")

    dats, funs, strs, oths = collect_globals(files)
    write_globals_h(dats, funs, strs, oths)
    print(f"globals: {len(dats)} DAT_ / {len(funs)} FUN_ / {len(strs)} s_ / {len(oths)} others")
    print(f"wrote {GLOBALS_H.relative_to(ROOT)}")



    if not args.check:
        return

    # syntax-check each file
    cc = "arm-none-eabi-gcc"
    flags = ["-mcpu=cortex-m3", "-mthumb", "-fsyntax-only",
             "-Ifirmware", "-fno-builtin"]
    report = {}
    n_ok = n_fail = 0
    targets = files if not args.limit else files[:args.limit]
    for i, p in enumerate(targets):
        r = subprocess.run([cc, *flags, str(p)],
                           capture_output=True, text=True)
        ok = r.returncode == 0
        report[str(p.relative_to(ROOT))] = {"ok": ok, "err": r.stderr[:200]}
        if ok:
            n_ok += 1
        else:
            n_fail += 1
            if n_fail <= 15:
                first_err = (r.stderr.splitlines() or ["?"])[0]
                print(f"  FAIL {p.relative_to(ROOT)}: {first_err[:90]}")
        if (i + 1) % 500 == 0:
            print(f"  checked {i+1}/{len(targets)} (ok={n_ok} fail={n_fail})", flush=True)

    (ROOT / "build" / "compile_report.json").write_text(
        json.dumps(report, indent=1), encoding="utf-8")
    print(f"\n== syntax check: {n_ok} ok, {n_fail} fail ({len(targets)} total) ==")


if __name__ == "__main__":
    main()
